- appEnv: default
  db:
    env: dev
    skeletondb:
      driver: mysql
      useConnPool: true
      connMaxLifetimeMin: 1
      maxIdleConnSize: 5
      maxOpenConnSize: 5
      reader:
        urlQuery: charset=utf8mb4&parseTime=True&loc=Asia%2FTokyo
      writer:
        urlQuery: charset=utf8mb4&parseTime=True&loc=Asia%2FTokyo
  log:
    level: info
    format: json
    fullPath:
  web:
    port: 9999
    authCheck: true

- appEnv: local
  db:
    env: local
    skeletondb:
      reader:
        host: mysql
        port: 3306
        user: user_r
        pass: pass_r
      writer:
        host: mysql
        port: 3306
        user: user_w
        pass: pass_w
  log:
    level: debug
    format: console
    fullPath: /var/log/skeleton/app.log
  web:
    port: 9999
    authCheck: true

- appEnv: dev
  db:
    env: dev
    skeletondb:
      reader:
        host: # Cloud DB URL
        port: 3306
        user: user_r
        pass: pass_r
      writer:
        host: # Cloud DB URL
        port: 3306
        user: user_w
        pass: pass_w
  log:
    level: debug
    format: json
    fullPath:
  web:
    port: 9999
    authCheck: true

- appEnv: prd
  db:
    env: prd
    skeletondb:
      driver: mysql
      useConnPool: true
      connMaxLifetimeMin: 1
      maxIdleConnSize: 5
      maxOpenConnSize: 5
      reader:
        host: # Cloud DB URL
        port: 3306
        user: user_r
        pass: pass_r
      writer:
        host: # Cloud DB URL
        port: 3306
        user: user_w
        pass: pass_w
  log:
    level: info
    format: json
    fullPath:
  web:
    port: 9999
    authCheck: true
