- env: default
  log:
    level: info
    development: true
    disableCaller: false
    disableStacktrace: false
    sampling:
      initial: 100
      thereafter: 100
    encoding: json
    encoderConfig:
      messageKey: msg
      levelKey: level
      timeKey: time
      nameKey: log
      callerKey: caller
      functionKey: func
      stacktraceKey: stacktrace
      lineEnding: \n
      levelEncoder: capitalColor
      timeEncoder: iso8601
      durationEncoder: nanos
      callerEncoder: short
      nameEncoder: full
      consoleSeparator: \t
    outputPaths:
      - stdout
    errorOutputPaths:
      - stderr
  rest:
    port: 9999
    auth: false

- env: local
  log:
    level: debug
    encoding: console

- env: dev
  log:
    level: debug

- env: prd
  log:
    development: false
  rest:
    port: 8080
    auth: true
