version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: build/local/server.dockerfile
    image: local-twtr-server
    container_name: local-twtr-server
    depends_on:
      - mysql
    ports:
      - 9999:9999
    volumes:
      - .:/var/app/twtr
      - ./pkg/interface/twtrdb/dump:/var/dump
    networks:
      - twtr-server-mysql

  mysql:
    build:
      context: .
      dockerfile: build/local/mysql.dockerfile
    image: local-twtr-mysql
    container_name: local-twtr-mysql
    ports:
      - 9998:3306
    volumes:
      - twtr-mysql:/var/lib/mysql
      - ./configs/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./pkg/interface/twtrdb/log:/var/log/mysql
    networks:
      - twtr-server-mysql

networks:
  twtr-server-mysql:

volumes:
  twtr-mysql: