// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/krtsato/go-server-templates/2021-05-twtr/pkg/interface"
	"github.com/krtsato/go-server-templates/2021-05-twtr/pkg/interface/rest"
	"github.com/krtsato/go-server-templates/2021-05-twtr/pkg/interface/rest/controller"
	"github.com/krtsato/go-server-templates/2021-05-twtr/pkg/interface/rest/router"
)

// Injectors from wire.go:

func InjectDependencies() _interface.Server {
	systemController := controller.InjectSystemController()
	facade := router.InjectFacadeImpl(systemController)
	restRest := rest.InjectRest(facade)
	return restRest
}
