// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/krtsato/go-server-templates/2021-05-twtr/pkg/appintf/webapi"
	"github.com/krtsato/go-server-templates/2021-05-twtr/pkg/appintf/webapi/controller"
	"github.com/krtsato/go-server-templates/2021-05-twtr/pkg/appintf/webapi/router"
)

// Injectors from wire.go:

func InjectDependencies() webapi.Server {
	systemController := controller.InjectSystemControllerImpl()
	facade := router.InjectFacadeImpl(systemController)
	server := webapi.InjectChiServerImpl(facade)
	return server
}
